### ISSUE TITLE
Can't use optional chaining 

### ISSUE THREAD

**Issue by RusseII** [RusseII/telegram-standup-bot#3]
Nodejs 14+ is required for [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining). 

Vercel only supports v10 and v12 - https://vercel.com/docs/runtimes#official-runtimes/node-js/node-js-version

They won't be able to support v14 until it is supported by AWS - https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

**Comment by Geczy** [comment]
Fixed ! 

![image](https://user-images.githubusercontent.com/1036968/124933736-bac7aa00-dfc9-11eb-9bd6-a753f597312b.png)

**Comment by RusseII** [comment]
YAY!
